apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  labels:
    app: todoapp-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoapp-deployment

  template:
    metadata:
      labels:
        app: todoapp-deployment

    spec:
      containers:
      - name: nginx
        image: tahereem/todoapp:latest
        ports:
        - containerPort: 8000
